# Generated by Django 2.0.1 on 2018-01-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'approved')], default=1)),
            ],
            options={
                'permissions': (('draft', 'Can save as draft'), ('approved', 'Can save as approved')),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'approved')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='example',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Parent'),
        ),
    ]
