name: "Continuous Integration"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    services:
      postgres:
        image: postgres:12.5
        env:
          POSTGRES_DB: yoflow
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Build steps
      uses: ./.github/actions/drf-react-template-framework-build
      with:
        python-version: ${{ matrix.python }}
    - name: Test with pytest
      run: |
        poetry run pytest --cov
